### ISSUE TITLE
Merge supposse-process and supposse-stream

### ISSUE THREAD

**Issue by piranna** [jprichardson/node-suppose#12]
supposse-process is already attaching to the process streams, so it could be re-written as a wrapper for supposse-stream, removing duplicated code. Also both of them could be exported on supposse.js so check is not needed.

**Comment by jprichardson** [comment]
Definitely was thinking this. I wanted this module to work with any stream based API... so this change would work nicely.

**Comment by piranna** [comment]
Fixed in 0.4.0, clossing.
