### ISSUE TITLE
"sudo" command error

### ISSUE THREAD

**Issue by Chalin-Shi** [jprichardson/node-suppose#23]
### code

``` javascript
suppose('sudo touch', ['/123.txt']).when('Password:').respond('abcdefg\n');
```
### log

``` javascript
events.js:141
      throw er; // Unhandled 'error' event
Error: spawn sudo touch ENOENT
```

**Comment by piranna** [comment]
Touch is an argument of sudo.

**Comment by Chalin-Shi** [comment]
Like this?
suppose('sudo', ['touch /123.txt']);

**Comment by piranna** [comment]
'Touch' is another independent entry on the array.

**Comment by Chalin-Shi** [comment]
Already resolved it, 3Q very much. How great you are ! /微笑

**Comment by piranna** [comment]
You are welcome. Anyway, I think it's a bad practice to use 'sudo'
hardcoded in a script...

**Comment by Chalin-Shi** [comment]
Your suggestion is correct, but my friend want to do like this.Maybe he thinks safety.

**Comment by stevenvachon** [comment]
This can be closed too.
