### ISSUE TITLE
Am I doing something wrong?

### ISSUE THREAD

**Issue by stevenvachon** [jprichardson/node-suppose#30]
```js
const log = [];
const PassThrough = require("stream").PassThrough;
const stream = new PassThrough();

stream
.on("data", chunk => console.log(chunk.toString()))
.once("end", () => console.log("done"));

suppose("node", ["test/helpers/createdb"], { debug:stream })
.when("? Value for POSTGRES_HOST ()").respond("asdf\n")
.when("? Value for POSTGRES_HOST (localhost)").respond("\n")
.when("? Value for POSTGRES_NAME (todo)").respond("\n")
.when("? Value for POSTGRES_USER (todo)").respond("\n")
.when("? Value for POSTGRES_PASSWORD (todo)").respond("\n")
.once("error", error => done(error))
.end(() => {});
```

It logs:
```
? Value for POSTGRES_HOST ()
```
then hangs

**Comment by piranna** [comment]
Try using RegExp instead of strings for the matching.

**Comment by stevenvachon** [comment]
Thank you. Why does that make it work?

**Comment by piranna** [comment]
String matches exactly the end of the internal buffer while RegExp does it with all the buffer content. If there's another character like a space at the end, then the string will not match but the RegExp will do.

**Comment by stevenvachon** [comment]
Perhaps this lib should convert string input to RegExp to catch such trailing whitespace.

**Comment by piranna** [comment]
Pull-request is welcome :-)

**Comment by stevenvachon** [comment]
A test fails without me having edited anything. I don't know what the expected string should look like.

**Comment by piranna** [comment]
Test got random after using `node-pty`, probably your pull-request could help to fix it by always using internally RegExp, will need to check this after merge.

**Comment by piranna** [comment]
> We shouldn't base the test on npm init. It's brittle because npm can and has changed its CLI text.

Any suggestion?

**Comment by stevenvachon** [comment]
The only thing that I can think of is to roll our own.

**Comment by piranna** [comment]
For the moment I think this is low priority, if `npm init` output changes in the future and we need to add more features to these module, then we would be able to look at it then, for example update it for the new output. I think I needed to do it recently...

**Comment by stevenvachon** [comment]
Then we should `.skip` that test to prevent it from failing with npm@5
