### ISSUE TITLE
open Travis CI

### ISSUE THREAD

**Issue by stevenvachon** [jprichardson/node-suppose#32]
I cannot view this project's builds, and instead see:

> This is not an active repository
You don't have sufficient rights to enable this repo on Travis.
Please contact the admin to enable it or to receive admin rights yourself.

This is preventing PRs from using CI.

**Comment by piranna** [comment]
I think this is something that @jprichardson needs to do, or give me transfer of the repo to my user. How do you see it?

**Comment by stevenvachon** [comment]
@jprichardson hello?

**Comment by jprichardson** [comment]
Done.
