### ISSUE TITLE
Function as response value

### ISSUE THREAD

**Issue by stevenvachon** [jprichardson/node-suppose#34]
Because of https://github.com/jprichardson/node-suppose/blob/master/lib/suppose-stream.js#L75, this will do nothing:

```js
.when("something").respond(match => "response")
```

Is there some other reason that the code supports a function value?

**Comment by piranna** [comment]
> this will do nothing

What do you mean by "nothing"? Is not `response` given to the stream?


> Is there some other reason that the code supports a function value?

It allow to generate responses based on the matched content that fired it, instead of only return static string.

**Comment by stevenvachon** [comment]
> Is not `response` given to the stream?
No, because the `push()` is only performed in the `else`
